name: cuda_env
channels:
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - cuda=12.3.1=0
  - cuda-cccl=12.3.101=0
  - cuda-command-line-tools=12.3.1=0
  - cuda-compiler=12.3.1=0
  - cuda-cudart=12.3.101=0
  - cuda-cudart-dev=12.3.101=0
  - cuda-cudart-static=12.3.101=0
  - cuda-cuobjdump=12.3.101=0
  - cuda-cupti=12.3.101=0
  - cuda-cupti-static=12.3.101=0
  - cuda-cuxxfilt=12.3.101=0
  - cuda-demo-suite=12.3.101=0
  - cuda-documentation=12.3.101=0
  - cuda-driver-dev=12.3.101=0
  - cuda-gdb=12.3.101=0
  - cuda-libraries=12.3.1=0
  - cuda-libraries-dev=12.3.1=0
  - cuda-libraries-static=12.3.1=0
  - cuda-nsight=12.3.101=0
  - cuda-nsight-compute=12.3.1=0
  - cuda-nvcc=12.3.103=0
  - cuda-nvdisasm=12.3.101=0
  - cuda-nvml-dev=12.3.101=0
  - cuda-nvprof=12.3.101=0
  - cuda-nvprune=12.3.101=0
  - cuda-nvrtc=12.3.103=0
  - cuda-nvrtc-dev=12.3.103=0
  - cuda-nvrtc-static=12.3.103=0
  - cuda-nvtx=12.3.101=0
  - cuda-nvvp=12.3.101=0
  - cuda-opencl=12.3.101=0
  - cuda-opencl-dev=12.3.101=0
  - cuda-profiler-api=12.3.101=0
  - cuda-runtime=12.3.1=0
  - cuda-sanitizer-api=12.3.101=0
  - cuda-toolkit=12.3.1=0
  - cuda-tools=12.3.1=0
  - cuda-visual-tools=12.3.1=0
  - gds-tools=1.8.1.2=0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=12.3.4.1=0
  - libcublas-dev=12.3.4.1=0
  - libcublas-static=12.3.4.1=0
  - libcufft=11.0.12.1=0
  - libcufft-dev=11.0.12.1=0
  - libcufft-static=11.0.12.1=0
  - libcufile=1.8.1.2=0
  - libcufile-dev=1.8.1.2=0
  - libcufile-static=1.8.1.2=0
  - libcurand=10.3.4.101=0
  - libcurand-dev=10.3.4.101=0
  - libcurand-static=10.3.4.101=0
  - libcusolver=11.5.4.101=0
  - libcusolver-dev=11.5.4.101=0
  - libcusolver-static=11.5.4.101=0
  - libcusparse=12.2.0.103=0
  - libcusparse-dev=12.2.0.103=0
  - libcusparse-static=12.2.0.103=0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnpp=12.2.3.2=0
  - libnpp-dev=12.2.3.2=0
  - libnpp-static=12.2.3.2=0
  - libnvjitlink=12.3.101=0
  - libnvjitlink-dev=12.3.101=0
  - libnvjpeg=12.3.0.81=0
  - libnvjpeg-dev=12.3.0.81=0
  - libnvjpeg-static=12.3.0.81=0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - nsight-compute=2023.3.1.1=0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3=py311h06a4308_0
  - python=3.11.5=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.0.0
      - accelerate==0.24.1
      - aiohttp==3.9.1
      - aioprometheus==23.3.0
      - aiosignal==1.3.1
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attention-sinks==0.3.1.dev0
      - attributedict==0.3.0
      - attrs==23.1.0
      - autoawq==0.1.7
      - babel==2.14.0
      - beautifulsoup4==4.12.2
      - bertviz==1.4.0
      - bitsandbytes==0.41.1
      - bleach==6.1.0
      - blessings==1.7
      - boto3==1.28.74
      - botocore==1.31.74
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - codecov==2.1.13
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colour-runner==0.1.1
      - comm==0.2.0
      - contourpy==1.1.1
      - coverage==7.3.2
      - cycler==0.12.1
      - dataproperty==1.0.1
      - datasets==2.14.7
      - debugpy==1.8.0
      - decorator==4.4.2
      - deepdiff==6.7.1
      - defusedxml==0.7.1
      - dill==0.3.7
      - distlib==0.3.7
      - distro==1.8.0
      - einops==0.7.0
      - executing==2.0.1
      - fastapi==0.104.1
      - fastjsonschema==2.19.0
      - filelock==3.13.1
      - fonttools==4.43.1
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - h11==0.14.0
      - httpcore==1.0.2
      - httptools==0.6.1
      - httpx==0.25.2
      - huggingface-hub==0.17.3
      - humanfriendly==10.0
      - idna==3.4
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - inspecta==0.1.3
      - ipykernel==6.26.0
      - ipython==8.17.2
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.3.2
      - json5==0.9.14
      - jsonlines==4.0.0
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - jupyter-client==8.6.0
      - jupyter-core==5.5.0
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.1
      - jupyter-server==2.12.1
      - jupyter-server-terminals==0.5.0
      - jupyterlab==4.0.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.2
      - jupyterlab-widgets==3.0.9
      - kaleido==0.2.1
      - kiwisolver==1.4.5
      - lm-eval==0.3.0
      - markupsafe==2.1.3
      - matplotlib==3.8.1
      - matplotlib-inline==0.1.6
      - mbstrdecoder==1.1.3
      - mistune==3.0.2
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - multiprocess==0.70.15
      - nbclient==0.9.0
      - nbconvert==7.12.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nltk==3.8.1
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - numexpr==2.8.7
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.3.7
      - ordered-set==4.1.0
      - orjson==3.9.10
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.1.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathvalidate==3.2.0
      - patsy==0.5.3
      - pexpect==4.8.0
      - pillow==10.1.0
      - platformdirs==4.0.0
      - plotly==5.18.0
      - pluggy==1.3.0
      - portalocker==2.8.2
      - proglog==0.1.10
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.39
      - protobuf==4.25.1
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==14.0.1
      - pyarrow-hotfix==0.6
      - pybind11==2.11.1
      - pycountry==22.3.5
      - pycparser==2.21
      - pydantic==1.10.13
      - pygments==2.16.1
      - pyparsing==3.1.1
      - pyproject-api==1.6.1
      - pytablewriter==1.2.0
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - quantile-python==1.1
      - ray==2.8.1
      - referencing==0.31.1
      - regex==2023.10.3
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rootpath==0.1.1
      - rouge-score==0.1.2
      - rpds-py==0.13.2
      - s3transfer==0.7.0
      - sacrebleu==1.5.0
      - safetensors==0.4.0
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - send2trash==1.8.2
      - sentencepiece==0.1.99
      - six==1.16.0
      - sklearn==0.0.post10
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlitedict==2.1.0
      - stack-data==0.6.3
      - starlette==0.27.0
      - statsmodels==0.14.0
      - sympy==1.12
      - tabledata==1.3.3
      - tabulate==0.9.0
      - tcolorpy==0.1.4
      - tenacity==8.2.3
      - termcolor==2.4.0
      - terminado==0.18.0
      - texttable==1.7.0
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tokenizers==0.14.1
      - toml==0.10.2
      - torch==2.1.0
      - torchaudio==2.1.1
      - torchvision==0.16.0
      - tornado==6.3.3
      - tox==4.11.4
      - tqdm==4.66.1
      - tqdm-multiprocess==0.0.11
      - traitlets==5.13.0
      - transformers==4.35.2
      - triton==2.1.0
      - typepy==1.3.2
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==2.1.0
      - uvicorn==0.24.0.post1
      - uvloop==0.19.0
      - virtualenv==20.25.0
      - vllm==0.2.3
      - watchfiles==0.21.0
      - wcwidth==0.2.9
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - websockets==12.0
      - widgetsnbextension==4.0.9
      - xformers==0.0.22.post7
      - xxhash==3.4.1
      - yarl==1.9.3
      - zstandard==0.22.0
prefix: /home/eron/miniconda3/envs/cuda_env
